### ISSUE TITLE
HTML Link not being generated when source is SCSS file

### ISSUE THREAD

**Issue by bram-pkg** [ElMassimo/vite-plugin-manifest-sri#1]
I am using a setup with SCSS / JS. Whenever I add the SRI Vite plugin, no manifest entry for the converted CSS file exists.

**Comment by ElMassimo** [comment]
By default, VIte does not add CSS files to the manifest.

If you extend the manifest to include CSS files, then this plugin will [read the file](https://github.com/ElMassimo/vite-plugin-manifest-sri/blob/main/src/index.ts#L43) and [add an integrity hash](https://github.com/ElMassimo/vite-plugin-manifest-sri/blob/main/src/index.ts#L57).

For example, _Vite Ruby_ creates a `manifest-assets.json` to keep track of CSS entrypoints, and this plugin will calculate the integrity hash and add it to the manifest entries.0

**Comment by bram-pkg** [comment]
Very weird, Laravel Vite keeps track of the scss file (converted to css) in the manifest, except when I enable the SRI plugin, it is removed from the manifest.

Any idea why this could be happening?

**Comment by ElMassimo** [comment]
Since this plugin reads the manifest from disk, and then writes it back, it should not remove any entries.

Only thing I can think of is a [race condition of some sort](https://github.com/innocenzi/laravel-vite/blob/main/vite-plugin-laravel/src/manifest.ts#L96-L110) with the laravel plugin. Might want to ask the maintainer to see if he has seen this behavior you are describing, and provide a minimal reproduction.

Try adding `vite-plugin-manifest-sri` __before/after__ the laravel plugin and see if that makes a difference.

**Comment by bram-pkg** [comment]
I can try make an issue on their repo, however changing the ordering in `vite.config.js` does not make any difference.
